name: Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 21

            - name: Install bun
              run: |
                    curl -fsSL https://bun.sh/install | bash
                    source /root/.bashrc

            - name: Clone Rin repository
              uses: actions/checkout@v2
              with:
                path: Rin

            - name: Install dependencies
              run: |
                    cd Rin/
                    bun i

            - name: Deploy
              run: |
                    cd Rin/
                    bun server/migrator.ts