name: SEO Workflow

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Rin repository
        uses: actions/checkout@v4
        with:
          path: Rin

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Set up Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev
          npx puppeteer browsers install chrome

      - name: Run script
        env: # Or as an environment variable
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_REGION: ${{ vars.S3_REGION }}
          S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
          FRONTEND_URL: ${{ vars.FRONTEND_URL }}
          SEO_BASE_URL: ${{ vars.SEO_BASE_URL }}
          SEO_CONTAINS_KEY: ${{ vars.SEO_CONTAINS_KEY }}
          S3_ACCESS_HOST: ${{ vars.S3_ACCESS_HOST }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}
          S3_CACHE_FOLDER: ${{ vars.S3_CACHE_FOLDER }}
          S3_FORCE_PATH_STYLE: ${{ vars.S3_FORCE_PATH_STYLE }}
        run: |
          cd Rin/
          bun i
          bun scripts/render.ts
